# Generated by Django 4.2 on 2024-12-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the banner', max_length=200)),
                ('image', models.FileField(help_text='Upload banner image', upload_to='banners/')),
                ('link', models.URLField(blank=True, help_text='URL to redirect when banner is clicked', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the banner currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
