# Generated by Django 4.2 on 2024-11-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorder',
            old_name='status',
            new_name='payment_status',
        ),
        migrations.AddField(
            model_name='userorder',
            name='delivery_status',
            field=models.CharField(choices=[('not delivered', 'Not Delivered'), ('delivered', 'Delivered')], default='not delivered', max_length=20),
        ),
    ]
