# Generated by Django 4.2 on 2025-01-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variantImage',
            field=models.FileField(blank=True, default=None, null=True, upload_to='productsVariants/'),
        ),
    ]
