# Generated by Django 4.2 on 2025-01-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productvariant_variantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='payment_method',
            field=models.CharField(default='cod', max_length=20),
        ),
    ]
