# Generated by Django 4.2 on 2024-11-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0002_alter_coupon_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
