# Generated by Django 4.2 on 2024-12-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0003_alter_coupon_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='commision',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
