# Generated by Django 4.2 on 2024-12-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='nid_no',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='trade_license',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
