# Generated by Django 4.2 on 2024-12-11 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_useraccount_nid_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='users/profiles'),
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid_no', models.CharField(max_length=20)),
                ('nid_front_image', models.FileField(blank=True, null=True, upload_to='documents/nid/front')),
                ('nid_back_image', models.FileField(blank=True, null=True, upload_to='documents/nid/back')),
                ('trade_license', models.CharField(max_length=100)),
                ('trade_license_image', models.FileField(blank=True, null=True, upload_to='documents/tradelicense')),
                ('store_name', models.CharField(max_length=255)),
                ('store_logo', models.FileField(blank=True, null=True, upload_to='store/logos')),
                ('store_email', models.EmailField(max_length=255)),
                ('store_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid_no', models.CharField(max_length=20)),
                ('nid_front_image', models.FileField(blank=True, null=True, upload_to='documents/nid/front')),
                ('nid_back_image', models.FileField(blank=True, null=True, upload_to='documents/nid/back')),
                ('trade_license', models.CharField(max_length=100)),
                ('trade_license_image', models.FileField(blank=True, null=True, upload_to='documents/tradelicense')),
                ('business_name', models.CharField(max_length=255)),
                ('business_logo', models.FileField(blank=True, null=True, upload_to='business/logos')),
                ('business_email', models.EmailField(max_length=255)),
                ('business_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
