# Generated by Django 4.2 on 2024-12-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
