# Generated by Django 4.2 on 2024-12-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_useraccount_is_blocked_useraccount_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
