# Generated by Django 4.2 on 2024-10-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cateogry_name',
            new_name='category_name',
        ),
    ]
