# Generated by Django 4.2 on 2024-10-24 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childcategory_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_categories', to='core.category')),
                ('subcategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_categories', to='core.subcategory')),
            ],
        ),
    ]
