# Generated by Django 4.2 on 2024-10-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_childcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childcategory',
            old_name='modified_date',
            new_name='modified_at',
        ),
    ]
