# Generated by Django 4.2 on 2024-10-26 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_modified_date_childcategory_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='core.category')),
                ('childcategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='core.childcategory')),
                ('subcategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='core.subcategory')),
            ],
        ),
    ]
