# Generated by Django 4.2 on 2024-12-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home_view',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
