# Generated by Django 4.2 on 2025-01-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0015_productvariant_variantimage'),
        ('payment_gateway', '0002_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionBkash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255, unique=True)),
                ('bkash_url', models.URLField()),
                ('callback_url', models.URLField()),
                ('success_callback_url', models.URLField()),
                ('failure_callback_url', models.URLField()),
                ('cancelled_callback_url', models.URLField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_status', models.CharField(default='Initiated', max_length=50)),
                ('merchant_invoice_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bkash_transactions', to='products.userorder')),
            ],
        ),
    ]
