# Generated by Django 4.2 on 2025-01-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField()),
            ],
        ),
    ]
